tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'autojump'
brew 'direnv'
brew 'git'
brew 'node-build'
brew 'ruby-build'
brew 'tree'

brew 'autoconf'
brew 'automake'
brew 'coreutils'
brew 'gpg'
brew 'libtool'
brew 'libxslt'
brew 'libyaml'
brew 'openssl'
brew 'readline'
brew 'unixodbc'

cask '1password'
cask 'alfred'
cask 'dash4'
cask 'dropbox'
cask 'firefox'
cask 'iterm2'
cask 'logitech-camera-settings'
cask 'rectangle'
cask 'setapp'
cask 'slack'
cask 'visual-studio-code'
cask 'whatsapp'

cask 'font-fira-mono'
