tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'asdf'
brew 'autojump'
brew 'direnv'
brew 'git'
brew 'node-build'
brew 'ruby-build'
brew 'tree'

brew 'autoconf'
brew 'automake'
brew 'coreutils'
brew 'fop'
brew 'gpg'
brew 'libtool'
brew 'libxslt'
brew 'libyaml'
brew 'openssl'
brew 'readline'
brew 'unixodbc'
brew 'wxwidgets'

cask '1password'
cask 'alfred'
cask 'dash6'
cask 'dropbox'
cask 'google-drive'
cask 'iterm2'
cask 'logitech-camera-settings'
cask 'rectangle'
cask 'setapp'
cask 'slack'
cask 'visual-studio-code'
cask 'whatsapp'

cask 'font-fira-mono'
cask 'font-fira-mono-for-powerline'
