#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_in_yellow '\nSetting up - brew - configuration... '

ask_for_confirmation 'Install brew packages?'

if answer_is_yes; then
  brew update
  brew bundle

  print_success
else
  print_in_purple 'Skipping brew'
fi
