#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_in_yellow 'Setting up - Codex - skills... '

mkdir -p ~/.config/dox-agent
ln -sfn "${DOTFILES_TEMPLATES}/skills" ~/.config/dox-agent/skills

print_success
