#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_in_yellow '\nSetting up git configuration... '

# Create symbolic link to default files
ln -sf ${DOTFILES_TEMPLATES}/.gitconfig ~/.gitconfig
ln -sf ${DOTFILES_TEMPLATES}/.gitconfig.personal ~/.gitconfig.personal
ln -sf ${DOTFILES_TEMPLATES}/.gitconfig.work ~/.gitconfig.work
ln -sf ${DOTFILES_TEMPLATES}/.gitignore ~/.gitignore

print_in_green 'Done!'
