#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_in_yellow 'Setting up - shell - configuration... '

ln -sf ${DOTFILES_TEMPLATES}/.zshrc ~/.zshrc
ln -sf ${DOTFILES_TEMPLATES}/.zshenv ~/.zshenv
ln -sf ${DOTFILES_TEMPLATES}/.default-gems ~/.default-gems

mkdir -p ~/.config/ghostty
ln -sf "${DOTFILES_TEMPLATES}/ghostty/config.ghostty" ~/.config/ghostty/config.ghostty

mkdir -p ~/.zsh/completion
mkdir -p ~/.zsh/functions
ln -sf ${DOTFILES_TEMPLATES}/zshfunctions/* ~/.zsh/functions

print_success
